// This file is generated by scripts/generate-sidebar.mjs. Do not edit manually.
import type { DefaultTheme } from 'vitepress'

export const sidebar: DefaultTheme.Sidebar = {
  "/python/": [
    {
      "text": "Python",
      "link": "/python/"
    },
    {
      "text": "第 1 章 必备基础知识",
      "link": "/python/01-必备基础知识"
    },
    {
      "text": "第 2 章 初识 Python",
      "link": "/python/02-初识Python"
    },
    {
      "text": "第 3 章 Python 核心基础",
      "link": "/python/03-Python核心基础"
    },
    {
      "text": "第 4 章 流程控制语句",
      "link": "/python/04-流程控制语句"
    },
    {
      "text": "第 5 章 函数入门",
      "link": "/python/05-函数入门"
    },
    {
      "text": "第 6 章 数据容器",
      "link": "/python/06-数据容器"
    },
    {
      "text": "第 7 章  面向对象",
      "link": "/python/07-面向对象"
    },
    {
      "text": "第 8 章 函数进阶",
      "link": "/python/08-函数进阶"
    },
    {
      "text": "第 9 章 错误与异常",
      "link": "/python/09-错误与异常"
    },
    {
      "text": "第 10 章 模块与包",
      "link": "/python/10-模块与包"
    },
    {
      "text": "第 11 章 迭代器 vs 生成器",
      "link": "/python/11-迭代器vs生成器"
    },
    {
      "text": "第 12 章 文件操作",
      "link": "/python/12-文件操作"
    },
    {
      "text": "第 13 章 进程与线程",
      "link": "/python/13-进程与线程"
    },
    {
      "text": "第 14 章 协程",
      "link": "/python/14-协程"
    }
  ],
  "/LangChain_1.2/": [
    {
      "text": "LangChain 1.2",
      "link": "/LangChain_1.2/"
    },
    {
      "text": "第01章：LangChain 1.2 概述",
      "link": "/LangChain_1.2/01-LangChain概述"
    },
    {
      "text": "第02章：模型的创建与调用",
      "link": "/LangChain_1.2/02-模型的创建与调用"
    },
    {
      "text": "第03章：LangSmith基本使用",
      "link": "/LangChain_1.2/03-LangSmith的使用"
    },
    {
      "text": "第04章：消息与提示词模板",
      "link": "/LangChain_1.2/04-Message与提示词模板"
    },
    {
      "text": "第05章：Tools",
      "link": "/LangChain_1.2/05-Tools"
    },
    {
      "text": "第06章：结构化输出(Structured Output)",
      "link": "/LangChain_1.2/06-结构化输出"
    },
    {
      "text": "第07章：智能体",
      "link": "/LangChain_1.2/07-智能体"
    },
    {
      "text": "第08章：中间件（Middleware）",
      "link": "/LangChain_1.2/08-中间件"
    },
    {
      "text": "第09章：上下文与记忆",
      "link": "/LangChain_1.2/09-上下文与记忆"
    },
    {
      "text": "第10章：RAG（Retrieval）",
      "link": "/LangChain_1.2/10-RAG"
    }
  ],
  "/LangGraph/": [
    {
      "text": "LangGraph",
      "link": "/LangGraph/"
    },
    {
      "text": "00. 环境配置",
      "link": "/LangGraph/00-环境配置"
    },
    {
      "text": "1. LangGraph总览",
      "link": "/LangGraph/01-LangGraph基础入门"
    },
    {
      "text": "4. 控制流",
      "link": "/LangGraph/02-LangGraph控制流与节点执行"
    },
    {
      "text": "6. 持久化机制和可恢复执行",
      "link": "/LangGraph/03-LangGraph持久化与记忆管理"
    },
    {
      "text": "8. 中断",
      "link": "/LangGraph/04-LangGraph中断与工具与部署"
    },
    {
      "text": "11. 流式执行",
      "link": "/LangGraph/05-LangGraph高级特性"
    }
  ]
}

export const categorySummaries = [
  {
    "key": "python",
    "text": "Python",
    "path": "/python/",
    "description": "从基础语法到并发编程",
    "count": 14,
    "firstArticle": "/python/01-必备基础知识"
  },
  {
    "key": "langchain",
    "text": "LangChain 1.2",
    "path": "/LangChain_1.2/",
    "description": "模型、工具、智能体与 RAG",
    "count": 10,
    "firstArticle": "/LangChain_1.2/01-LangChain概述"
  },
  {
    "key": "langgraph",
    "text": "LangGraph",
    "path": "/LangGraph/",
    "description": "有状态工作流与智能体运行时",
    "count": 6,
    "firstArticle": "/LangGraph/00-环境配置"
  }
] as const

export const orderedArticleLinks = [
  {
    "title": "第 1 章 必备基础知识",
    "link": "/python/01-必备基础知识",
    "categoryKey": "python"
  },
  {
    "title": "第 2 章 初识 Python",
    "link": "/python/02-初识Python",
    "categoryKey": "python"
  },
  {
    "title": "第 3 章 Python 核心基础",
    "link": "/python/03-Python核心基础",
    "categoryKey": "python"
  },
  {
    "title": "第 4 章 流程控制语句",
    "link": "/python/04-流程控制语句",
    "categoryKey": "python"
  },
  {
    "title": "第 5 章 函数入门",
    "link": "/python/05-函数入门",
    "categoryKey": "python"
  },
  {
    "title": "第 6 章 数据容器",
    "link": "/python/06-数据容器",
    "categoryKey": "python"
  },
  {
    "title": "第 7 章  面向对象",
    "link": "/python/07-面向对象",
    "categoryKey": "python"
  },
  {
    "title": "第 8 章 函数进阶",
    "link": "/python/08-函数进阶",
    "categoryKey": "python"
  },
  {
    "title": "第 9 章 错误与异常",
    "link": "/python/09-错误与异常",
    "categoryKey": "python"
  },
  {
    "title": "第 10 章 模块与包",
    "link": "/python/10-模块与包",
    "categoryKey": "python"
  },
  {
    "title": "第 11 章 迭代器 vs 生成器",
    "link": "/python/11-迭代器vs生成器",
    "categoryKey": "python"
  },
  {
    "title": "第 12 章 文件操作",
    "link": "/python/12-文件操作",
    "categoryKey": "python"
  },
  {
    "title": "第 13 章 进程与线程",
    "link": "/python/13-进程与线程",
    "categoryKey": "python"
  },
  {
    "title": "第 14 章 协程",
    "link": "/python/14-协程",
    "categoryKey": "python"
  },
  {
    "title": "第01章：LangChain 1.2 概述",
    "link": "/LangChain_1.2/01-LangChain概述",
    "categoryKey": "langchain"
  },
  {
    "title": "第02章：模型的创建与调用",
    "link": "/LangChain_1.2/02-模型的创建与调用",
    "categoryKey": "langchain"
  },
  {
    "title": "第03章：LangSmith基本使用",
    "link": "/LangChain_1.2/03-LangSmith的使用",
    "categoryKey": "langchain"
  },
  {
    "title": "第04章：消息与提示词模板",
    "link": "/LangChain_1.2/04-Message与提示词模板",
    "categoryKey": "langchain"
  },
  {
    "title": "第05章：Tools",
    "link": "/LangChain_1.2/05-Tools",
    "categoryKey": "langchain"
  },
  {
    "title": "第06章：结构化输出(Structured Output)",
    "link": "/LangChain_1.2/06-结构化输出",
    "categoryKey": "langchain"
  },
  {
    "title": "第07章：智能体",
    "link": "/LangChain_1.2/07-智能体",
    "categoryKey": "langchain"
  },
  {
    "title": "第08章：中间件（Middleware）",
    "link": "/LangChain_1.2/08-中间件",
    "categoryKey": "langchain"
  },
  {
    "title": "第09章：上下文与记忆",
    "link": "/LangChain_1.2/09-上下文与记忆",
    "categoryKey": "langchain"
  },
  {
    "title": "第10章：RAG（Retrieval）",
    "link": "/LangChain_1.2/10-RAG",
    "categoryKey": "langchain"
  },
  {
    "title": "00. 环境配置",
    "link": "/LangGraph/00-环境配置",
    "categoryKey": "langgraph"
  },
  {
    "title": "1. LangGraph总览",
    "link": "/LangGraph/01-LangGraph基础入门",
    "categoryKey": "langgraph"
  },
  {
    "title": "4. 控制流",
    "link": "/LangGraph/02-LangGraph控制流与节点执行",
    "categoryKey": "langgraph"
  },
  {
    "title": "6. 持久化机制和可恢复执行",
    "link": "/LangGraph/03-LangGraph持久化与记忆管理",
    "categoryKey": "langgraph"
  },
  {
    "title": "8. 中断",
    "link": "/LangGraph/04-LangGraph中断与工具与部署",
    "categoryKey": "langgraph"
  },
  {
    "title": "11. 流式执行",
    "link": "/LangGraph/05-LangGraph高级特性",
    "categoryKey": "langgraph"
  }
] as const
