import { readFile } from 'node:fs/promises'
import { mkdir, rename, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import {
  buildSidebar,
  CONTENT_CATEGORIES,
  scanContent
} from './lib/content.mjs'

const CATEGORY_DIRECTORIES = {
  python: 'python',
  langchain: 'LangChain_1.2',
  langgraph: 'LangGraph'
}

export async function generateSidebar(rootDir = process.cwd()) {
  const entriesByCategory = Object.fromEntries(await Promise.all(CONTENT_CATEGORIES.map(async (category) => [
    category.key,
    await scanContent(join(rootDir, CATEGORY_DIRECTORIES[category.key]), category)
  ])))
  const allEntries = CONTENT_CATEGORIES.flatMap((category) => entriesByCategory[category.key])
  const sidebar = buildSidebar(entriesByCategory)
  const categorySummaries = CONTENT_CATEGORIES.map((category) => {
    const articles = entriesByCategory[category.key].filter((entry) => !entry.isIndex)
    return {
      key: category.key,
      text: category.text,
      path: category.path,
      description: category.description,
      count: articles.length,
      firstArticle: articles[0]?.route ?? null
    }
  })
  const orderedArticleLinks = allEntries
    .filter((entry) => !entry.isIndex)
    .map((entry) => ({ title: entry.title, link: entry.route, categoryKey: entry.categoryKey }))
  const source = renderSidebar({ sidebar, categorySummaries, orderedArticleLinks })
  const destination = join(rootDir, '.vitepress', 'sidebar.ts')

  let existing = null
  try {
    existing = await readFile(destination, 'utf8')
  } catch (error) {
    if (error.code !== 'ENOENT') throw error
  }

  if (existing === source) return false

  await mkdir(join(rootDir, '.vitepress'), { recursive: true })
  const temporaryDestination = `${destination}.${process.pid}.tmp`
  await writeFile(temporaryDestination, source)
  await rename(temporaryDestination, destination)
  return true
}

function renderSidebar({ sidebar, categorySummaries, orderedArticleLinks }) {
  return `// This file is generated by scripts/generate-sidebar.mjs. Do not edit manually.\nimport type { DefaultTheme } from 'vitepress'\n\nexport const sidebar: DefaultTheme.Sidebar = ${JSON.stringify(sidebar, null, 2)}\n\nexport const categorySummaries = ${JSON.stringify(categorySummaries, null, 2)} as const\n\nexport const orderedArticleLinks = ${JSON.stringify(orderedArticleLinks, null, 2)} as const\n`
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const changed = await generateSidebar()
  console.log(changed ? 'Generated .vitepress/sidebar.ts' : '.vitepress/sidebar.ts is current')
}
